### ISSUE TITLE
Information about persistence

### ISSUE THREAD

**Issue by btoro** [IHTSDO/snowstorm-lite#14]
How can I keep the data I upload persistent? I'm using the manual approach to load the snomed files. If there is a directory or volume where its stored, that would be ideal.

Thanks!

**Comment by OOub** [comment]
Got the same issue on a Kubernetes deployment. 
The lucene index is not persistent on pod restart.

I tried mounting the folder `/app/lucene-index` in a persistent volume but I get this error: 
No segments* file found in mmapdirectory: ... [lost+found]

**Comment by kaicode** [comment]
If running as a Java application (see [Running with Java Guide](https://github.com/IHTSDO/snowstorm-lite/blob/master/docs/running-with-java.md)) the Lucene index is created in the directory `lucene-index` in the working directory, wherever the java command is run.

When running under Docker a Volume is automatically created with a random name and the content is stored there. I am able to start and stop the `snowstorm-lite` Docker container and the loaded SNOMED CT edition is still there when listing CodeSystems.

I'm not sure if Lucene will work with a mounted directory, I have not tried that. Google / ChatGPT is your friend.

**Comment by btoro** [comment]
I managed to get it to persist, but I had to change the lucene index directory so its not on a mount point. When I skipped that, it threw some errors for me. 

Here's the arg I used to change the lucene index path:
`"--index.path=lucene-index/data"`

And then I mounted a volume here:
```
          volumeMounts:
            - name: lucene-index-volume
              mountPath: /app/lucene-index
```

My argocd deployment file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowstorm
  namespace: snowstorm
  labels:
    app.kubernetes.io/name: snowstorm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snowstorm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snowstorm
    spec:
      containers:
        - name: snowstorm-lite
          image: snomedinternational/snowstorm-lite:latest
          args: ["--admin.password=test", "--index.path=lucene-index/data"]
          volumeMounts:
            - name: lucene-index-volume
              mountPath: /app/lucene-index
      volumes:
        - name: lucene-index-volume
          persistentVolumeClaim:
            claimName: snowstorm-lucene-index-pvc
```
